#!/Users/arch/.local/share/sketchybar_lua/lua

local user = os.getenv("USER")
local config_dir = os.getenv("CONFIG_DIR") or ("/Users/" .. user .. "/.config/sketchybar")
local lua_module_dir = "/Users/" .. user .. "/.local/share/sketchybar_lua"

os.execute(string.format(
  '[ -d "%s" ] || (' ..
  '/usr/bin/git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && ' ..
  'cd /tmp/SbarLua && /usr/bin/make install && ' ..
  '/bin/cp /tmp/SbarLua/lua-5.5.0/src/lua "%s/lua" && ' ..
  'rm -rf /tmp/SbarLua' ..
  ')',
  lua_module_dir,
  lua_module_dir
))

package.path = table.concat({
  package.path,
  config_dir .. "/?.lua",
  config_dir .. "/?/init.lua",
}, ";")

package.cpath = table.concat({
  package.cpath,
  lua_module_dir .. "/?.so",
}, ";")

sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()
sbar.event_loop()
